authorCreate:
  path: /api/v1/authors
  methods: POST
  controller: App\Controller\AuthorController::create
getAllWithBookCount:
  path: /api/v1/authors/list
  methods: GET
  controller: App\Controller\AuthorController::getAllWithBookCount
authorGet:
  path: /api/v1/authors/{id}
  methods: GET
  controller: App\Controller\AuthorController::read
authorUpdate:
  path: /api/v1/authors/update
  methods: POST
  controller: App\Controller\AuthorController::update
authorDelete:
  path: /api/v1/authors/{id}
  methods: DELETE
  controller: App\Controller\AuthorController::delete

bookCreate:
  path: /api/v1/books
  methods: POST
  controller: App\Controller\BookController::create
getAllWithAuthorName:
  path: /api/v1/books/list
  methods: GET
  controller: App\Controller\BookController::getAllWithAuthorName
bookGet:
  path: /api/v1/books/{id}
  methods: GET
  controller: App\Controller\BookController::read
bookUpdate:
  path: /api/v1/books/update
  methods: POST
  controller: App\Controller\BookController::update
bookDelete:
  path: /api/v1/books/{id}
  methods: DELETE
  controller: App\Controller\BookController::delete

getAllBookAuthor:
  path: /public/api/v1/all
  methods: GET
  controller: App\Controller\PublicController::getAllBookAuthor